############### Login Info
GET http://localhost:3000/loginInfo/1/4SF18CS005 HTTP/1.1

##################  Mark Answer 
GET http://localhost:3000/markAnswer/1/4SF18CS14?q=3&a=2 HTTP/1.1

############ Submit 
GET http://localhost:3000/submit/1/4SF18CS1 HTTP/1.1

############################### Login 
POST http://localhost:3000/user/login HTTP/1.1
content-type: application/json

{
    "u_id":"4SF18CS144",
    "a_id":"1",
    "password":"dw"
}
############################### Login 
POST https://assessmentApi.examvedha.com/user/login HTTP/1.1
content-type: application/json

{
    "u_id":"4SF18CS144",
    "a_id":"1",
    "password":"dw"
}
###############################
GET https://assessmentApi.examvedha.com