############### Login Info
GET http://localhost:8080/loginInfo/4/4SF18CS144 HTTP/1.1

##################  Mark Answer 
GET http://localhost:8080/markAnswer/4/4SF18CS144?q=5&a=-1 HTTP/1.1

############ Submit 
GET http://localhost:8080/submit/4/4SF18CS144 HTTP/1.1

############################### Login 
POST http://localhost:8080/user/login HTTP/1.1
content-type: application/json

{
    "u_id":"4SF18CS144",
    "a_id":"4",
    "password":"dw"
}
############################### Login 
POST https://assessmentApi.examvedha.com/user/login HTTP/1.1
content-type: application/json

{
    "u_id":"4SF18CS144",
    "a_id":"4",
    "password":"dw"
}
###############################
GET https://assessmentApi.examvedha.com